[2024-09-06T14:16:21.279+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-06T14:16:21.288+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: async_flow.update_db_task manual__2024-09-06T14:16:20.396338+00:00 [queued]>
[2024-09-06T14:16:21.292+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: async_flow.update_db_task manual__2024-09-06T14:16:20.396338+00:00 [queued]>
[2024-09-06T14:16:21.293+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-06T14:16:21.299+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): update_db_task> on 2024-09-06 14:16:20.396338+00:00
[2024-09-06T14:16:21.302+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=470) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-06T14:16:21.303+0000] {standard_task_runner.py:72} INFO - Started process 471 to run task
[2024-09-06T14:16:21.304+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'async_flow', 'update_db_task', 'manual__2024-09-06T14:16:20.396338+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/dags_async_flow.py', '--cfg-path', '/tmp/tmpz0o_rx09']
[2024-09-06T14:16:21.304+0000] {standard_task_runner.py:105} INFO - Job 110: Subtask update_db_task
[2024-09-06T14:16:21.328+0000] {task_command.py:467} INFO - Running <TaskInstance: async_flow.update_db_task manual__2024-09-06T14:16:20.396338+00:00 [running]> on host a3a5f1897683
[2024-09-06T14:16:21.369+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='async_flow' AIRFLOW_CTX_TASK_ID='update_db_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-06T14:16:20.396338+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-06T14:16:20.396338+00:00'
[2024-09-06T14:16:21.369+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-06T14:16:21.376+0000] {dags_async_flow.py:29} INFO - Starting operation...
[2024-09-06T14:16:21.409+0000] {dags_async_flow.py:40} INFO - Updated 5000 documents
[2024-09-06T14:16:21.409+0000] {dags_async_flow.py:42} INFO - Operation completed
[2024-09-06T14:16:21.410+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-06T14:16:21.416+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-06T14:16:21.416+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=async_flow, task_id=update_db_task, run_id=manual__2024-09-06T14:16:20.396338+00:00, execution_date=20240906T141620, start_date=20240906T141621, end_date=20240906T141621
[2024-09-06T14:16:21.442+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-06T14:16:21.452+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-06T14:16:21.453+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
