[2024-09-06T17:43:13.340+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-06T17:43:13.350+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: async_flow.sum manual__2024-09-06T17:43:02.727107+00:00 [queued]>
[2024-09-06T17:43:13.354+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: async_flow.sum manual__2024-09-06T17:43:02.727107+00:00 [queued]>
[2024-09-06T17:43:13.354+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-06T17:43:13.359+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): sum> on 2024-09-06 17:43:02.727107+00:00
[2024-09-06T17:43:13.362+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=378) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-06T17:43:13.363+0000] {standard_task_runner.py:72} INFO - Started process 382 to run task
[2024-09-06T17:43:13.364+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'async_flow', 'sum', 'manual__2024-09-06T17:43:02.727107+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/dags_async_flow.py', '--cfg-path', '/tmp/tmpsqu7qi1u']
[2024-09-06T17:43:13.365+0000] {standard_task_runner.py:105} INFO - Job 226: Subtask sum
[2024-09-06T17:43:13.386+0000] {task_command.py:467} INFO - Running <TaskInstance: async_flow.sum manual__2024-09-06T17:43:02.727107+00:00 [running]> on host 0817eb6c24af
[2024-09-06T17:43:13.423+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='async_flow' AIRFLOW_CTX_TASK_ID='sum' AIRFLOW_CTX_EXECUTION_DATE='2024-09-06T17:43:02.727107+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-06T17:43:02.727107+00:00'
[2024-09-06T17:43:13.424+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-06T17:43:13.425+0000] {dags_async_flow.py:39} INFO - Summing values: LazySelectSequence([50 items])
[2024-09-06T17:43:13.425+0000] {python.py:240} INFO - Done. Returned value was: {{ task_instance.xcom_pull(task_ids='sum', dag_id='adhoc_airflow', key='return_value') }}
[2024-09-06T17:43:13.429+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 789, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session_or_null)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3638, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 249, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 686, in serialize_value
    return pickle.dumps(value)
           ^^^^^^^^^^^^^^^^^^^
_pickle.PicklingError: Can't pickle <function sum at 0xffffac05a7a0>: it's not the same object as unusual_prefix_d2f08847d6bfa3fd2a7f9cce8743e824d5526626_dags_async_flow.sum
[2024-09-06T17:43:13.433+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=async_flow, task_id=sum, run_id=manual__2024-09-06T17:43:02.727107+00:00, execution_date=20240906T174302, start_date=20240906T174313, end_date=20240906T174313
[2024-09-06T17:43:13.438+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-06T17:43:13.438+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 226 for task sum (Can't pickle <function sum at 0xffffac05a7a0>: it's not the same object as unusual_prefix_d2f08847d6bfa3fd2a7f9cce8743e824d5526626_dags_async_flow.sum; 382)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 789, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session_or_null)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3638, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 249, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 686, in serialize_value
    return pickle.dumps(value)
           ^^^^^^^^^^^^^^^^^^^
_pickle.PicklingError: Can't pickle <function sum at 0xffffac05a7a0>: it's not the same object as unusual_prefix_d2f08847d6bfa3fd2a7f9cce8743e824d5526626_dags_async_flow.sum
[2024-09-06T17:43:13.464+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-06T17:43:13.473+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-06T17:43:13.474+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
